# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'version.py'

jobs:
  build_and_publish_pypi:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      version_file: "version.py"
      setup_py: "setup.py"
      publish_prerelease: true
